name: proyecto_final
description: "Proyecto final de desarrollos de aplicaciones."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Network
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # Media
  image_picker: ^1.0.4
  video_player: ^2.7.2
  
  # Utils
  url_launcher: ^6.2.1
  intl: ^0.18.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true